import type { StressTestResult } from "../../types";

export function ExplanationNote({ result }: { result: StressTestResult }) {
  return (
    <div className="border-l-2 border-accent/50 pl-4">
      <div className="font-mono text-[11px] uppercase tracking-wider text-ink-tertiary">
        Why This Matters
      </div>
      <p className="mt-2 font-serif text-base leading-relaxed text-ink">{result.explanation}</p>
      {result.concentration_notes.length > 0 && (
        <ul className="mt-3 space-y-1">
          {result.concentration_notes.map((note, i) => (
            <li key={i} className="text-sm text-ink-secondary">
              · {note}
            </li>
          ))}
        </ul>
      )}
      <p className="mt-3 font-mono text-[10px] uppercase tracking-wider text-ink-tertiary">
        Deterministic rule-based analysis — not generated by a live AI model
      </p>
    </div>
  );
}
